const PDFDocument = require('pdfkit');

/**
 * Vercel Serverless Function: Generate a simple payment receipt PDF.
 * NOTE: This runs only on Vercel. When served statically (e.g. via `serve` or `python3 -m http.server`)
 * the `/api/payment-receipt` path will not execute this code.
 */
module.exports = async (req, res) => {
  try {
    const query = req.query || {};
    const paymentId = (query.paymentId || 'PYT-demo').toString();
    const amount = (query.amount || '0.00 USD').toString();
    const receiver = (query.receiverName || 'NovaQuill Ltd').toString();
    const createdAt = (query.dateTime || new Date().toLocaleString('en-GB', { hour12: false })).toString();

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const pdfBuffer = Buffer.concat(chunks);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader(
        'Content-Disposition',
        `attachment; filename="payment-receipt-${paymentId}.pdf"`
      );
      res.status(200).send(pdfBuffer);
    });

    // Header
    doc.fontSize(20).text('Payment advice', { align: 'left' });
    doc.moveDown();

    // Meta
    doc.fontSize(12);
    doc.text(`Status: Payment sent`);
    doc.text(`Payment ID: ${paymentId}`);
    doc.text(`Sent date: ${createdAt}`);
    doc.moveDown();

    // Parties
    doc.fontSize(14).text('Sender', { underline: true });
    doc.fontSize(12);
    doc.text('AGP Technology');
    doc.text('9 Temasek Boulevard, Singapore 038989');
    doc.text('info@agptechnology.com');
    doc.moveDown();

    doc.fontSize(14).text('Receiver', { underline: true });
    doc.fontSize(12);
    doc.text(receiver);
    doc.moveDown();

    // Settlement
    doc.fontSize(14).text('Settlement', { underline: true });
    doc.fontSize(12);
    doc.text(`Payment amount: ${amount}`);
    doc.moveDown();

    // Footer note (shortened version of on-page declaration)
    doc.fontSize(10);
    doc.moveDown();
    doc.text(
      'This receipt is generated by the XREX Pay prototype for demonstration purposes only.',
      { align: 'left' }
    );

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
};


